BUILD_LOG_TAIL = 256
GENERIC = "GENERIC"
INFERENCE_TEMPERATURE = 0.01
INFERENCE_MAX_TOKENS = 8192
TOP_N_ERRROS = 10
MAX_CONTEXT_SIZE = 6100
MAX_PREVIEW_CONTENT = 1024
SLACK_POLL_INTERVAL = 10
INFERENCE_MAX_TOOL_ITERATIONS = 5
PR_ANALYSIS_MAX_TOOL_ITERATIONS = (
    15  # PR analysis needs more iterations for funnel investigation approach
)
INFERENCE_API_TIMEOUT_SECONDS = 120  # seconds
INFERENCE_API_RETRY_ATTEMPTS = 3
INFERENCE_API_RETRY_DELAY = 5.0  # seconds
INFERENCE_API_MAX_RETRY_DELAY = 60.0  # seconds
INFERENCE_API_RETRY_BACKOFF_MULTIPLIER = 2.0
MAINTENANCE_ISSUE = "Maintenance Issue"
SUMMARY_LOOKBACK_SECONDS_DEFAULT = 30 * 60
RAG_TOP_K_DEFAULT = 3
MAX_PR_DIFF_SIZE = 20000
MAX_CHANGED_FILES_RESULTS = 50
MAX_PR_COMMITS_RESULTS = 50
MAX_PR_COMMENTS_SIZE = 10000
